### ISSUE TITLE
Support `login` field for autotype

### ISSUE THREAD

**Issue by xeruf** [wosc/pass-autotype#1]
If the entry contains a `login` field but no `user` field, the "Autotype" option is not available, even though these should be equivalent here?

Other than that, thank you very much for this handy tool :)

**Comment by wosc** [comment]
Firstly, sorry that I'm so very late here. Secondly, I'm not sure I understand the situation you're describing. The _default_ autotype setting is `:user |Tab :password |Return`. If that doesn't work for _some_ passwords, you can set a field called `autotype` in that password to use as the autotype setting for that password. If the default doesn't work for _all_ of your passwords, due to systematic naming differences, you'll need to edit the `AUTOTYPE_DEFAULT` variable in the code to match the field names you are using.
